name: TreeCuter
version: '${version}'
main: pl.norbit.treecuter.TreeCuter
api-version: 1.17
author: Norbit4
website: 'https://github.com/Norbit4'
softdepend:
  - WorldGuard
  - ItemsAdder
  - PlaceholderAPI
commands:
  treecuter:
    aliases:
      - tc
    description: TreeCuter main command.
    usage: /treecuter